#############################################################################
# Makefile for building: Serial
# Generated by qmake (3.1) (Qt 5.12.9)
# Project:  Serial.pro
# Template: app
# Command: /opt/Qt5.12.9/5.12.9/gcc_64/bin/qmake -o Makefile Serial.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.12.9/5.12.9/gcc_64/include -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I. -I/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.12.9/5.12.9/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt5.12.9/5.12.9/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt5.12.9/5.12.9/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Serial1.0.0
DISTDIR = /home/octopus/QT/Serial/.tmp/Serial1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.12.9/5.12.9/gcc_64/lib
LIBS          = $(SUBLIBS) /opt/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Widgets.so /opt/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Gui.so /opt/Qt5.12.9/5.12.9/gcc_64/lib/libQt5SerialPort.so /opt/Qt5.12.9/5.12.9/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp moc_widget.cpp
OBJECTS       = main.o \
		widget.o \
		moc_widget.o
DIST          = /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/lex.prf \
		Serial.pro widget.h main.cpp \
		widget.cpp
QMAKE_TARGET  = Serial
DESTDIR       = 
TARGET        = Serial


first: all
####### Build rules

Serial: ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Serial.pro /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/lex.prf \
		Serial.pro
	$(QMAKE) -o Makefile Serial.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/toolchain.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qml_debug.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/qmake_use.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/lex.prf:
Serial.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Serial.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Serial

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp
moc_widget.cpp: widget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasictimer.h \
		moc_predefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/bin/moc
	/opt/Qt5.12.9/5.12.9/gcc_64/bin/moc $(DEFINES) --include /home/octopus/QT/Serial/moc_predefs.h -I/opt/Qt5.12.9/5.12.9/gcc_64/mkspecs/linux-g++ -I/home/octopus/QT/Serial -I/opt/Qt5.12.9/5.12.9/gcc_64/include -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort -I/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore -I. -I/usr/local/openssl/include -I/opt/st/stm32mp1/3.1-snapshot/sysroots/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/usr/include/c++/9.3.0 -I/opt/st/stm32mp1/3.1-snapshot/sysroots/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/usr/include/c++/9.3.0/arm-ostl-linux-gnueabi -I/opt/st/stm32mp1/3.1-snapshot/sysroots/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/usr/include/c++/9.3.0/backward -I/opt/st/stm32mp1/3.1-snapshot/sysroots/x86_64-ostl_sdk-linux/usr/lib/arm-ostl-linux-gnueabi/gcc/arm-ostl-linux-gnueabi/9.3.0/include -I/opt/st/stm32mp1/3.1-snapshot/sysroots/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/usr/lib/arm-ostl-linux-gnueabi/9.3.0/include -I/opt/st/stm32mp1/3.1-snapshot/sysroots/x86_64-ostl_sdk-linux/usr/lib/arm-ostl-linux-gnueabi/gcc/arm-ostl-linux-gnueabi/9.3.0/include-fixed -I/opt/st/stm32mp1/3.1-snapshot/sysroots/cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi/usr/include widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/opt/Qt5.12.9/5.12.9/gcc_64/bin/uic
	/opt/Qt5.12.9/5.12.9/gcc_64/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtguiglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtgui-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qrgba64.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPort \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialport.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/qbasictimer.h \
		ui_widget.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/QMessageBox \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qmessagebox.h \
		/opt/Qt5.12.9/5.12.9/gcc_64/include/QtWidgets/qdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Serial/bin || mkdir -p $(INSTALL_ROOT)/opt/Serial/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Serial/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Serial/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Serial/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

